version: "3"

services:
  app:
    build: ./php
    container_name: app
    restart: always
    working_dir: /application
    volumes:
      - ./application:/application
      - ./php/php-dev.ini:/usr/local/etc/php/php.ini
    links:
      - db

  nginx:
    image: nginx
    container_name: nginx
    restart: always
    working_dir: /application
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./application:/application
      - ./nginx/logs:/var/log/nginx
    links:
      - app
    ports:
      - 80:80

  db:
    image: mysql:5.6.41
    container_name: db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/logs:/var/log/mysql
    ports:
      - 3306:3306